### PR TITLE
Get Handel training step

### PR DESCRIPTION
**Pull request by rdzotz**
Might make more sense here to get the handle to the previous training run step in order to compare metrics stored.

### CODE REVIEW

**Review by mariamedp — CHANGES_REQUESTED** [review]
Makes sense to me, can we call it `parent_run` then to avoid confusion?

Also, I'm thinking maybe we could make the `is_new_model_better()` function a bit more illustrative. Could you please add an example line on how to get metrics? something like:
> metrics_new_model = parent_run.get_metrics()

**Comment by mariamedp** [comment]
Looks like I can't create a comment there, but please review line 33, it needs to be changed as well.

**Comment by mariamedp** [comment]
Side comment: notice this will not be the run corresponding to the train step, as you said, but the parent run of both training & evaluation steps (the run corresponding to the pipeline itself). When training happens, metrics are logged both in the child "train" run and in the parent "pipeline" run ([here](https://github.com/microsoft/dstoolkit-mlops-base/blob/b0beb744ebbcf0ca704e41638dc7d2498a0c7d26/src/train.py#L40)).

**Review by rdzotz — COMMENTED** [review]
Fixed this as the pipe handle returns a dictionary of each logged metric

**Pull request merged**
